server:
  port: 9201
  servlet:
    context-path: /cine/v1
spring:
  application:
    name: service-showtime
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:showtimeBD;
    driver-class-name: org.h2.Driver
    platform: h2
    username: sa
    password:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/
feign:
  circuitbreaker:
    enabled: true

